### PR TITLE
fix(x509): some fixes on the X509 salt internal pki

### PR DESCRIPTION
**Pull request by rgroux**
The fixes:
  - race condition: ensure the salt pki is ready
  - bug: the pyth3 version of salt minion have some issue to
    evaluate the reamining time of the certificate
  - pkg: use python-m2crypto on RedHat 8 os family distros

### CODE REVIEW

**Comment by valentin2105** [comment]
Can I merge ? It seem good to me. 
We should try on a single node - oneshot install to ensure it's fine

**Comment by rgroux** [comment]
i test it from 1 node as master and with salt master on the master node
and also on external salt master and with 3 kube master.

i am not very satisfy with what i wrote in the README_PKI, because it s not very clear about how to bootstrap the pki system. but the code is ok to me and i test it with a old version of salt (2018.2)

you told me you have issue i didn t reproduce in my setup, so you must try before merge in the setup (if you can) that already failed, or give me the exact setup , i will try to reproduce.

maybe i find the issue you get, i try to reproduce in a bare naive new salt master (external), and i catch some issue with state dependencies (require k8-worker.cni) path issue, presume.
so i will try to fix it, before you merge, i have another patch for stuff about that that will remove the modification, but i can be good to stay consistent and clear.


i will add some jinja map soon to be abble to manage various os_family and version (Centos 7/8 ubuntu 20.4, and also new arch like aarch64)

**Comment by rgroux** [comment]
it' s the lastest  patch, it use require and id instead a sls file. it s more robust and avoid issue with path.

**Comment by rgroux** [comment]
> Can I merge ? It seem good to me.
> We should try on a single node - oneshot install to ensure it's fine

is it ok for you?

**Comment by valentin2105** [comment]
> > Can I merge ? It seem good to me.
> > We should try on a single node - oneshot install to ensure it's fine
> 
> is it ok for you?

I'm out of work for few day due of familial hardship,
If you can try on a single node and if it's OK, I'll merge.
If you can't, I'll try that in next weeks and then merge.

Keep me in touch.

Thanks for your work @rgroux

**Comment by rgroux** [comment]
> > > Can I merge ? It seem good to me.
> > > We should try on a single node - oneshot install to ensure it's fine
> > 
> > 
> > is it ok for you?
> 
> I'm out of work for few day due of familial hardship,
> If you can try on a single node and if it's OK, I'll merge.
> If you can't, I'll try that in next weeks and then merge.
> 
> Keep me in touch.
> 
> Thanks for your work @rgroux

actually i try on a single node with salt master on it, and it works fine

and i have new patch for you soon to integrate new features.

**Comment by valentin2105** [comment]
Thanks @rgroux  !

**Pull request merged**
