### PR TITLE
x509 salt module/states instead of cfssl

### PR DESCRIPTION
**Pull request by rgroux**
this is a PR for #1 

it works well, but i think it can be useful to add some new parameters for signing policy in case of more than one  CA and in case of many kubernetes clusters.

### CODE REVIEW

**Comment by rgroux** [comment]
hi @valentin2105 

did you look at the PR ?

**Comment by valentin2105** [comment]
Hi @rgroux,

To be honest, I'm quite busy theses time so I didn't find the time to try it. 

For you, everything is ok ? You don't see any issue with this PR in 3 master topology ? 

Can you merge the latest commit from my master and After I will merge if you think that it's ready. ;)

Thanks Richard.

Have you a contact where I can reach you elsewhere than Github ?

**Comment by rgroux** [comment]
@valentin2105 

quite busy too. for me it s ok, with the 3 masters. il will merge your last commit into the PR in the next 2 days,.

Thanks

**Comment by rgroux** [comment]
@valentin2105 

i close and reopen a new PR, because i don t know how to modify a PR.

**Comment by rgroux** [comment]
PR #29

**Pull request closed without merging**
